# Generated by Django 5.1.6 on 2025-05-18 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('problem_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('problem_title', models.CharField(max_length=100, unique=True)),
                ('problem_description', models.TextField()),
                ('problem_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
