# Generated by Django 5.1.6 on 2025-05-24 06:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_alter_problem_problem_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('input', models.TextField()),
                ('expected_output', models.TextField()),
                ('output', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
