# Generated by Django 5.1.6 on 2025-05-24 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
